apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: {{ atoi .Values.envMap.VITE_PORT.value }}
      name: app
    - port: 3000
      name: status
  selector:
    app: {{ ternary "app" "disabled" .Values.enabled }}
